### ISSUE TITLE
Designing and developing the API

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#169]

**Comment by AoifeHughes** [comment]
https://alan-turing-institute.github.io/AssurancePlatform/platform-details/api/ is what's here already, would we want an API beyond what is offered here? Or to have this wrapped in something to make easily accessible from another language

**Comment by chrisdburr** [comment]
Your comments in today's meeting about the [SciVision](https://sci.vision/#/new-model) repo management are relevant here. 

The general goal here would be to allow users to query the full repository of assurance cases to identify common patterns (e.g. how many assurance cases address healthcare, how many have a goal related to explainability). This requires a bit of design work though, because it will mean making some of the metadata associated with assurance cases accessible (or FAIR, see #180).

**Comment by kallewesterling** [comment]
This issue consists of two actions: (1) designing an API structure and (2) developing its backend.

A clarification needed for me is whether we have an API structure currently? If so, why does it need designing/developing, and what value does it bring for us? These are questions that @chrisdburr would be best situated to answer.

Also: I am curious how we're thinking about this issue now that much work has taken place over the past two months (since the issue was opened), and (a) what work could be scoped from this, (b) what scoped work around this design and development process of the API will follow from #180 (especially after we split that issue up).
