### ISSUE TITLE
Setup Azure to properly redeploy when there is a change to the main branch here!

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#250]

**Comment by AoifeHughes** [comment]
@joseph-palmer would you have any idea why this isn't working on Azure side of things? No worries if not, I can investigate more widely.

![Screenshot 2023-10-19 at 08 07 03](https://github.com/alan-turing-institute/AssurancePlatform/assets/10923695/b04893a7-626d-441f-acd1-4bb2239f6b8d)

**Comment by joseph-palmer** [comment]
Have you added the webhook URL to the docker file? https://docs.docker.com/docker-hub/webhooks/

**Comment by kallewesterling** [comment]
This issue would certainly improve our workflow significantly and seems like a really good item to sail up to high priority for us. Let's chat a bit more in our planning meeting today, @AoifeHughes!

**Comment by edchapman88** [comment]
closed with #f152888a35fbe67714ec9ecab7cc043ef37afc4a, this is set up with the "container registry" source option in the azure app deployment centre (unchanged from whats shown in the screenshot above) - but now the webhooks for the frontend and the backend have been added to the repositories on Dockerhub so that new pushes to dockerhub trigger redeployment on azure.

**Comment by kallewesterling** [comment]
Thank you so much @edchapman88 !
