### ISSUE TITLE
Add to docs about permissions and access of GitHub API

### ISSUE THREAD

**Issue by AoifeHughes** [alan-turing-institute/AssurancePlatform#267]

**Comment by kallewesterling** [comment]
I’d add a link to this somewhere

https://docs.github.com/en/rest?apiVersion=2022-11-28

**Comment by kallewesterling** [comment]
Write up the reasons why we want access to public/private repos, email address and username (if we implement that)

**Comment by kallewesterling** [comment]
How's this @AoifeHughes?

-------

### Why We Ask for Your GitHub Login & Repository Access

We want to ensure transparency in how our platform works. So, why do we ask you to log in via GitHub and grant us certain permissions? Let's break it down:

1. We value your hard work and creativity. **By accessing your GitHub email and username, we can associate every assurance case you create on our platform with you.** This ensures that you get the credit for your work and can easily manage and revisit your projects anytime.

2. We want to present users with the convenience of having their assurance cases sync automatically with their GitHub repositories. **By accessing selected repositories, we can save your creations right to your GitHub.** This means less manual work for you and an integrated backup of your projects.

3. We use GitHub authentication because it's a secure way to handle user logins. **Instead of building a separate login system, which can be prone to security vulnerabilities, using GitHub means we can rely on their trusted security measures.**

4. We only ask for what we need. **Access to your email and username is to ensure your projects are correctly associated with you. And repository access is solely for the TEA platform's synchronisation feature.** We won't peek into unrelated content or make unwanted changes.

Remember, our core mission is to help you build ethical and trustworthy assurance cases. Your trust is paramount to us, and we're committed to ensuring the safety and integrity of your data.

**Comment by kallewesterling** [comment]
Do you think that the text above is sufficient for our users @AoifeHughes ? Have I captured the reasons why we ask for access to public/private repos?

**Comment by kallewesterling** [comment]
Should be resolved with PR #305, awaiting your reviews, @AoifeHughes + @chrisdburr
