### ISSUE TITLE
Prevent deletion of branches

### ISSUE THREAD

**Issue by chrisdburr** [alan-turing-institute/AssurancePlatform#297]
At the moment, if a parent claim is deleted all of its children are also deleted. This shouldn't happen. 

It would be fine for the disconnected branch to "float" until it is reconnected. 

However, the reconnection should only be a valid link (e.g. connecting a property claim to a strategy).

**Comment by kallewesterling** [comment]
@chrisdburr Can you try to rewrite this into a user story as well? A draft:

"As an authorised user, I want to have my disconnected branches of property claims and evidence [other elements?] floating while I create a new goal and later be able to reattach them to the new goal, so that I can more easily manage my assurance cases."

**Comment by kallewesterling** [comment]
Closing as this has been drafted into a user story in #439.
