### ISSUE TITLE
Ensure token validity is checked

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#349]
If there is an existing but invalid token in the browser, the auto-login is successful (because it doesn't actually check that token is valid, only that it exists), and then the 401 responses from the backend are unhandled.

**Comment by edchapman88** [comment]
With db3b4261dcbe2a0dbfaa80e0789a38a19c90009c I have handled 404 (not found) and 401 (unauthorised) responses from the `getCase` endpoint, and the call to `/cases` from the manageCases page; redirecting to a Not Found page and a "login session expired" page/flow, respectively.

This approach has not added any token validation to the auto-login, but instead catches the 404 as soon as the first request is made to the backend (because I think the auth system needs reconsidering).

In the process I have had a look through the general authentication infrastructure and I think there should be a discussion around what the goal/requirement is for user management.

- If it tool is to be cloud deployed, my suggestion would be to leverage the cloud provider's IAM (identity access management) tools. Eg. They have end-user pools to automatically and **securely** store log in credentials, and they provide cloud api's to securely submit information to these pools.
- Is a full password based authentication necessary? Alternatives would be to manage access with just usernames to demonstrate that the tool is in a development state, or offer **only** SSO oAuth functionality - eg. let google and github handle sensitive user account info, and use oAuth to provide sessions for the TEA app.
- In my opinion, the halfway house currently implemented is not ideal:
  - Passwords are collected at signup and then sent **unencrypted** over the network to the backend.
    - This is currently live in the version deployed on azure, and if users are under the impression that the authentication is securely implemented, they may input and **compromise a password that they use for other real-world, sensitive accounts.**
  - I haven't looked into how the backend manages user session and tokens, but tokens flows are complex and not secure if improperly implemented (eg. there should be intermittent token refreshing).
  - If user account info **must** be stored locally in the backend database (a last resort in my opinion), it is crucial that it the implementation stays up to date with best practices (eg. secret salt and pepper), and there will be data protection considerations too.

**Comment by kallewesterling** [comment]
I know Aoife had some problems with how to implement the login, because we wanted to steer clear of saving too much personal data on our local storage. (This whole conversation happened after the big BL hack.)

From your comments, though, it seems like you have already thought through this halfway house that we’ve implemented. You also seem a lot more read-up on this than what we currently have… I do have a few follow up questions:

- Would there be a way to implement an IAM tool through Azure by chance? (bearing in mind that we wouldn’t want to lock down the future users of the platform to a particular cloud provider)
- Are there any drawbacks with using SSO oAuth? (beyond the fact that not all end-users might have a GitHub account, although I suppose that these days we can almost assume that everyone would have a Google account…)

**Comment by edchapman88** [comment]
1. I'm pretty sure there would be an equivalent on Azure, though i'm not familiar with it. My experience was with a native mobile React app with an AWS backend, and the way this was implemented **did** lock the app in to AWS, because the AWS SDK (software development kit) is used in the source code to hook up to all of the AWS services in the backend (including the user pool and auth services).

1.b There are probably guidelines/ examples somewhere on how best to set up authentication in a **backend agnostic** way, so that the code base is as ready as possible for a developer to come along and finish/customise the app to meet there specific needs (eg. an AWS, Azure or on premise backend) - but I have no experience with this.

2. No drawbacks spring to mind w.r.t using oAuth with another provider eg. google - but i've not had direct experience with this (just slightly adjacent experience implementing oAuth between two backends). I think it could be a good option given that it would be a useful starting point for a developer to then add a cloud based authentication service alongside the google oAuth if they wanted to.

**Comment by kallewesterling** [comment]
Let's have a quick chat about this on Monday. I am curious and interested to hear what your opinion on what we should do, moving forward!
