### ISSUE TITLE
[User Story]: Preserve Child Elements on Parent Deletion

### ISSUE THREAD

**Issue by kallewesterling** [alan-turing-institute/AssurancePlatform#439]
### Role

As an assurance case editor

### Desired Feature

I want child elements to remain in the assurance case even if their parent element is deleted, allowing them to "float" until reconnected appropriately

### Benefit

So that I can manage the structure of the assurance case more flexibly without losing data inadvertently when modifying higher-level elements

### Acceptance Criteria

GIVEN a parent element is deleted,
WHEN I navigate to the assurance case view,
THEN the child elements of the deleted parent should still be visible and unlinked in the assurance case.
AND I should be able to reconnect these floating elements to other valid parent elements within the assurance case according to the defined linking rules (e.g., a property claim can only be connected to a strategy or another property claim).

### Dependencies

- [ ] Review and update of the current deletion logic to ensure child elements are preserved and not automatically deleted.
- [ ] Develop a UI mechanism that allows users to visually identify and reconnect floating elements.

### Technical Notes

- Implement logic to mark elements as "floating" when their parent is deleted.
- Ensure reconnection actions are constrained to valid parent-child relationships to maintain the integrity of the assurance case structure.
- Consider adding visual cues or a separate workspace area within the UI to manage floating elements effectively.
- Accessibility considerations: Ensure that all new UI components are accessible, including proper keyboard navigation and screen reader support for managing floating elements.

### Definition of Done

- [ ] The feature fulfills all acceptance criteria.
- [ ] The code is reviewed and meets team coding standards.
- [ ] All unit, integration, and end-to-end tests are passed.
- [ ] The feature meets accessibility standards set for the project.
- [ ] The code passes the CI/CD pipeline quality controls (style and linting).
- [ ] The feature is merged into the main branch.
- [ ] The feature is deployed and functional in the QA environment.
- [ ] The feature was demonstrated to the team and accepted by the product owner.

**Comment by cptanalatriste** [comment]
@RichGriff , in the development branch now there's a working version of the new endpoints for this issue. At the moment, **it only works on Context elements**:

* First, there are some database changes. Please run `python manage.py migrate` before testing the code.
* For placing an existing Context element in the "sandbox",  do a `POST` request to `contexts/<context_id>/detach`, without a payload.  The response is just a status code.
* For attaching a Context element to an existing Goal, do a `POST` request to `contexts/<context_id>/attach`, with payload `{goal_id: <goal_id>}`.The response is just a status code.
* For retrieve the contents of the Sandbox, do a `GET` request to `cases/<assurance_case_id>/sandbox` without a payload. The JSON response will have the format `{contexts: [<all Context elements in Sandbox>]}`

In the following days, I will be adding support to the rest of the case elements.

**Comment by RichGriff** [comment]
@cptanalatriste just a quick update from me on my changes:

- User can now `detach` a `context` element
- User will see a banner notifying them that there are orphaned elements linked to this case
- User can find `existing elements` (orphaned elements) when editing a node. This is a different action to creating a new child element
- User can select an `orphan` to `attach` (this list is filtered based on what can be added to the parent node)
- User can then choose to `delete all` orphans that they see in the list above

https://github.com/alan-turing-institute/AssurancePlatform/assets/28445922/6bfedc21-3d61-4f24-9f30-1beb597d11a6

I've tried to make this versatile for all types but will need to review once you have completed them.

**Comment by kallewesterling** [comment]
Oh, I really like how this looks!

**Comment by cptanalatriste** [comment]
@RichGriff , just updated the branch with the endpoints for attaching Evidence:

* For placing an existing Evidence element in the "sandbox",  do a `POST` request to `evidence/<evidence_id>/detach`,  with payload `{property_claim_id: <parent_property_claim_id>}`.  The response is just a status code.
* For attaching a Evidence element to an existing Property Claim, do a `POST` request to `evidence/<evidence_id >/attach`, with payload  `{property_claim_id: <new_property_claim_id>}`. The response is just a status code.
* For retrieve the contents of the Sandbox, do a `GET` request to `cases/<assurance_case_id>/sandbox` without a payload. The JSON response will have the format `{contexts: [<all Context elements in Sandbox>], evidence: [<all Evidence elements in Sandbox>]}`

In the following days, I will be adding support to the rest of the case elements.

**Comment by cptanalatriste** [comment]
@RichGriff, just updated the branch with the endpoints for attaching Property Claims:

* For placing an existing Property Claim element in the "sandbox",  do a `POST` request to `propertyclaims/<property_claim_id>/detach`, with payload `{goal_id: <parent_goal_id>, property_claim_id: <parent_property_claim_id>, strategy_id: <parent_strategy_id>}`. You only need to include the ID of the parent element you want to detach (e.g. for detaching from a goal use `{goal_id: 123}`).  The response is just a status code.
* For attaching a Property Claim element to an existing case element, do a `POST` request to `propertyclaims/<property_claim_id>/attach`, with payload   `{goal_id: <parent_goal_id>, property_claim_id: <parent_property_claim_id>, strategy_id: <parent_strategy_id>}`.  You only need to include the ID of the parent element you want to attach. The response is just a status code.
* For retrieve the contents of the Sandbox, do a `GET` request to `cases/<assurance_case_id>/sandbox` without a payload. The JSON response will have the format `{contexts: [<all Context elements in Sandbox>], evidence: [<all Evidence elements in Sandbox>], property_claims: [<all Property Claim elements in the Sandbox>] }`

**IMPORTANT:** Attaching/Detaching property claims do not break the connections between that property claim and its child elements. This means that if you detach a property claim with the structure `P1 -> P.1.1 -> E1`, moving P1 to the sandbox will actually move the whole branch. Also, if you attach `P1` to another element, you will also be attaching the whole branch.

@chrisdburr is this the expected behaviour?   

In the following days, I will be adding support to the rest of the case elements.

**Comment by chrisdburr** [comment]
> **IMPORTANT:** Attaching/Detaching property claims do not break the connections between that property claim and its child elements. This means that if you detach a property claim with the structure `P1 -> P.1.1 -> E1`, moving P1 to the sandbox will actually move the whole branch. Also, if you attach `P1` to another element, you will also be attaching the whole branch.
> 
> @chrisdburr is this the expected behaviour?

@cptanalatriste, yes that's what I'd expect to happen. After all, the evidence and sub property claims only make sense in relation to their linked parent.

**Comment by cptanalatriste** [comment]
@RichGriff after this PR https://github.com/alan-turing-institute/AssurancePlatform/pull/538 , when retrieving sandbox contents now we also include the child elements of strategies and property claims (as you pointed out, before only IDs where included).

I just merged the PR into `develop`, so it should be available in staging shortly.

**Comment by cptanalatriste** [comment]
@chrisdburr , please provide the new text for the model when deleting.

**Comment by chrisdburr** [comment]
> [@chrisdburr](https://github.com/chrisdburr) , please provide the new text for the model when deleting.

Do you mean 'modal' rather than 'model'? If so, please go with the following:

> Are you sure?
>Deleting this element will also remove all of the connected child elements. Please detach any child elements that you wish to keep before deleting, as the current action cannot be undone.

**Comment by chrisdburr** [comment]
Thanks. Closing issue.
